@startuml fresh-guard-erd

entity users {
    +id: VARCHAR(20)
    name: VARCHAR(100)
    username: VARCHAR(100)
    password: VARCHAR(100)
    profile_picture_name: VARCHAR(255)
    profile_picture_path: VARCHAR(255)
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    deleted_at: TIMESTAMP
    --
}

entity scan_results {
    +id: VARCHAR(20)
    *user_id: VARCHAR(20)
    *produce_id: VARCHAR(20)
    freshness_score: DECIMAL(3,2)
    is_tracked: BOOLEAN
    created_at: TIMESTAMP
    --
}

entity produces {
    +id: VARCHAR(20)
    name: VARCHAR(100)
    calories: INT
    protein: INT
    carbohydrates: INT 
    fiber: INT
    vitamin_a: INT
    vitamin_d: INT
    vitamin_c: INT
    --
}

entity stores {
    +id: VARCHAR(20)
    name : VARCHAR(100)
    description: TEXT
    address: TEXT
    operation_time: VARCHAR(100)
    phone: VARCHAR(20)
    gmap_url: VARCHAR(200)
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    deleted_at: TIMESTAMP
    --
}

entity store_galeries {
    +id: VARCHAR(20)
    *store_id: VARCHAR(20)
    name: VARCHAR(100)
    path: VARCHAR(255)
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    deleted_at: TIMESTAMP
    --
}

entity favorite_stores {
    *user_id: VARCHAR(20)
    *store_id: VARCHAR(20)
    --
}

entity products {
    +id: VARCHAR(20)
    *store_id: VARCHAR(20)
    *product_categories_id: VARCHAR(20)
    name: VARCHAR(100)
    description: TEXT
    price: DECIMAL(12,2)
    stock: INT
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    deleted_at: TIMESTAMP
    ---
}

entity product_categories {
    +id: VARCHAR(20)
    category: VARCHAR(100)
}

' Relations
users --o{ scan_results
scan_results }o-- produces
users --o{ favorite_stores
stores --o{ favorite_stores
stores --o{ products
products }o-- product_categories
stores --o{ store_galeries
@enduml