openapi: 3.0.3
info:
  title: Authentication API
  description: API for Authentication
  version: 1.0.0
servers:
  - url: https://{domain}/api
    description: Fresh Guard API Server
    variables:
      domain:
        default: localhost
        enum:
          - localhost
          - prod
          - not-ready-yet

paths:
  /auth/login:
    post:
      summary: Login
      description: API for Login and get Authentication Token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: adam_123
                password:
                  type: string
                  example: "password_1234"
              required:
                - username
                - password
      responses:
        "201":
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                      username: 
                        type: string
              examples:
                ucup:
                  value:
                    status: success
                    message: Login berhasil
                    data:
                      token: "eyJhbGciOiJIUz"
                      user:
                        username: ucup
        "400":
          description: Kesalahan data yang dikirimkan user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                example:
                  message: 
                    - Username atau password salah
                    - Username tidak boleh mengandung spasi
                    - Username terlalu panjang
  /auth/register:
    post:
      summary: Register user
      description: Register akun user baru
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 4
                  maxLength: 100
                username:
                  type: string
                  minLength: 4
                  maxLength: 100
                  pattern: "[a-z0-9_]"
                  description: username hanya boleh huruf, angka dan underscore. Kalau username yang dikirimkan terdapat huruf besar akan otomatis dikonversi menjadi huruf kecil oleh backend 
                password:
                  type: string
            examples:
              ucup:
                value:
                  name: Ucup Ganteng
                  username: ucup_ganteng
                  password: ucup123
      responses:
          "200":
            description: Registrasi akun baru berhasil
            content:
              application/json:
                examples:
                  ucup:
                    value:
                      status: succes
                      message: Pendaftaran berhasil
                      data:
                        userId: 123
                        token: "_auth_token_here"
          "401":
            description: Pendaftaran akun gagal
            content:
              application/json:
                examples:
                  ucup:
                    value:
                      status: error
                      message: [username terlalu panjang, username telah digunakan]
            