openapi: 3.0.3
info:
  title: Scan Fruits and Vegetables API
  description: API for scan Fruits and Vegetables to assess freshness and rotteness
  version: 1.0.0
servers:
  - url: https://{domain}/api/v1
    description: Fresh Guard API Server
    variables:
      domain:
        default: localhost
        enum:
          - localhost
          - prod
          - not-ready-yet

paths:
  /scans/produce:
    post:
      summary: Scanning product freshness
      description: Endpoint for uploading image and freshness result
      parameters:
        - name: Authentication
          in: header
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Image of fruit/vegetable for scanning
                title:
                  type: string
                  description: Image title (opsional)
                  example: "apple.png"
              required:
                - image
      responses:
        "200":
          description: Image scann success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: 
                    type: object
                    properties:
                      freshness: 
                        type: number
                      rottenness: 
                        type: number
                      consumable:
                        type: boolean
